services:
  - type: web
    name: heva-creativehub
    env: static
    buildCommand: npm run render-build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
